'use strict';

require('dotenv').config();

const express = require('express');
const http    = require('http');
const path    = require('path');
const fs      = require('fs');
const { WebSocketServer } = require('ws');
const QRCode  = require('qrcode');
const { spawn } = require('child_process');

const PORT    = parseInt(process.env.DEPLOY_PORT || '4000', 10);
const ENV_FILE = path.resolve(__dirname, '.env');
const SESSION_DIR = path.resolve(__dirname, 'session');
const QR_FILE = path.resolve(__dirname, 'session', '.qr_pending');

const app    = express();
const server = http.createServer(app);
const wss    = new WebSocketServer({ server });

app.use(express.json());
app.use(express.static(path.resolve(__dirname, 'public')));
app.get('/', (req, res) => res.sendFile(path.resolve(__dirname, 'deploy.html')));

// ── broadcast ──
function broadcast(data) {
  const msg = JSON.stringify(data);
  wss.clients.forEach(ws => { if (ws.readyState === 1) ws.send(msg); });
}

// ── state ──
let botProcess  = null;
let isConnected = false;
let connectedAs = '';

// ── read current .env ──
app.get('/api/config', (req, res) => {
  const env = readEnv();
  res.json({
    ownerNumber: env.OWNER_NUMBER || '',
    mongoUri:    env.MONGODB_URI  || '',
    geminiKey:   env.GEMINI_API_KEY || '',
    botName:     env.BOT_NAME || 'REX-MD',
    prefix:      env.PREFIX  || '.',
    configured:  !!(env.OWNER_NUMBER && env.MONGODB_URI && env.GEMINI_API_KEY),
    connected:   isConnected,
    connectedAs,
  });
});

// ── save config & launch ──
app.post('/api/deploy', async (req, res) => {
  const { ownerNumber, mongoUri, geminiKey, botName, prefix } = req.body;
  if (!ownerNumber || !mongoUri || !geminiKey) {
    return res.status(400).json({ ok: false, error: 'Missing required fields' });
  }

  // Write .env
  const content = `# REX-MD — generated by deploy dashboard
SESSION_ID=REX-MD
OWNER_NUMBER=${ownerNumber.replace(/\D/g,'')}
USE_PAIRING_CODE=false
PREFIX=${prefix || '.'}
BOT_NAME=${botName || 'REX-MD'}

MONGODB_URI=${mongoUri}

GEMINI_API_KEY=${geminiKey}
GEMINI_MODEL_PRIMARY=gemini-2.5-flash-lite
GEMINI_MODEL_FALLBACK=gemini-2.5-flash

GROQ_API_KEY=
GROQ_MODEL=llama-3.3-70b-versatile

MAX_DOWNLOAD_MB=50
AUTO_STATUS_VIEW=true
AUTO_STATUS_REACT=false
STATUS_REACT_EMOJI=👀
COMMAND_COOLDOWN_MS=2000
OPENWEATHER_API_KEY=
ANTI_DELETE=false
LOG_LEVEL=info
`;
  fs.writeFileSync(ENV_FILE, content, 'utf8');

  // Clear session for fresh pair
  if (fs.existsSync(SESSION_DIR)) {
    fs.readdirSync(SESSION_DIR)
      .filter(f => f !== '.gitkeep')
      .forEach(f => { try { fs.unlinkSync(path.join(SESSION_DIR, f)); } catch {} });
  } else {
    fs.mkdirSync(SESSION_DIR, { recursive: true });
  }

  // Reload env
  Object.assign(process.env, parseEnvFile(content));

  // Kill existing bot
  if (botProcess) { try { botProcess.kill(); } catch {} botProcess = null; }
  isConnected = false;

  // Start bot
  startBot();
  res.json({ ok: true });
});

// ── restart ──
app.post('/api/restart', (req, res) => {
  if (botProcess) { try { botProcess.kill(); } catch {} botProcess = null; }
  isConnected = false;
  startBot();
  res.json({ ok: true });
});

// ── reset / logout ──
app.post('/api/reset', (req, res) => {
  if (botProcess) { try { botProcess.kill(); } catch {} botProcess = null; }
  isConnected = false;
  if (fs.existsSync(SESSION_DIR)) {
    fs.readdirSync(SESSION_DIR)
      .filter(f => f !== '.gitkeep')
      .forEach(f => { try { fs.unlinkSync(path.join(SESSION_DIR, f)); } catch {} });
  }
  broadcast({ type: 'reset' });
  res.json({ ok: true });
});

// ── status ──
app.get('/api/status', (req, res) => {
  res.json({ running: !!botProcess, connected: isConnected, connectedAs });
});

// ── launch index.js ──
function startBot() {
  if (botProcess) return;

  // Re-read env file so child inherits new values
  const envVars = fs.existsSync(ENV_FILE) ? parseEnvFile(fs.readFileSync(ENV_FILE,'utf8')) : {};

  botProcess = spawn('node', ['index.js'], {
    cwd: __dirname,
    env: { ...process.env, ...envVars },
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  broadcast({ type: 'bot_starting' });

  function onData(chunk) {
    const text = chunk.toString();
    process.stdout.write(text);

    if (text.includes('✅ Connected as')) {
      const m = text.match(/Connected as (.+)/);
      isConnected = true;
      connectedAs = m ? m[1].trim() : 'REX-MD';
      broadcast({ type: 'connected', name: connectedAs });
    }
    if (text.includes('Logged out') || text.includes('logged out')) {
      isConnected = false;
      broadcast({ type: 'logged_out' });
    }
    if (text.includes('FATAL') || text.includes('Cannot start')) {
      broadcast({ type: 'error', message: text.replace(/\[.*?\]\s*\w+:\s*/,'').trim() });
    }
  }

  botProcess.stdout.on('data', onData);
  botProcess.stderr.on('data', onData);
  botProcess.on('exit', (code) => {
    console.log(`[deploy] Bot exited (${code})`);
    botProcess = null;
    if (!isConnected) broadcast({ type: 'bot_exit', code });
  });
}

// ── poll QR file ──
async function pollQR() {
  try {
    if (fs.existsSync(QR_FILE)) {
      const raw = fs.readFileSync(QR_FILE, 'utf8').trim();
      if (raw) {
        fs.unlinkSync(QR_FILE);
        const dataUrl = await QRCode.toDataURL(raw, {
          errorCorrectionLevel: 'H', margin: 1,
          color: { dark: '#111827', light: '#ffffff' }, width: 300,
        });
        broadcast({ type: 'qr', image: dataUrl });
      }
    }
  } catch {}
}
setInterval(pollQR, 500);

// ── WS handshake ──
wss.on('connection', ws => {
  ws.send(JSON.stringify({ type: 'info', connected: isConnected, connectedAs }));
});

// ── helpers ──
function readEnv() {
  if (!fs.existsSync(ENV_FILE)) return {};
  return parseEnvFile(fs.readFileSync(ENV_FILE, 'utf8'));
}

function parseEnvFile(content) {
  const result = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    result[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return result;
}

// ── auto-start if already configured ──
const existingEnv = readEnv();
if (existingEnv.OWNER_NUMBER && existingEnv.MONGODB_URI && existingEnv.GEMINI_API_KEY) {
  const hasCreds = fs.existsSync(path.join(SESSION_DIR, 'creds.json'));
  if (hasCreds) {
    console.log('[deploy] Existing session found — auto-starting bot...');
    startBot();
  }
}

server.listen(PORT, () => {
  console.log(`\n🚀 REX-MD Deploy Dashboard → http://localhost:${PORT}\n`);
});
